package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.81

import (
	"context"

	"github.com/saisrikar/market-intel-platform/gateway/graph/model"
)

// TopStories is the resolver for the topStories field.
func (r *queryResolver) TopStories(ctx context.Context, ticker string, limit *int32) ([]*model.Story, error) {
	var requestedLimit int32
	if limit != nil {
		requestedLimit = *limit
	}

	stories, err := r.RankerClient.GetTopStories(ctx, ticker, requestedLimit)
	if err != nil {
		return nil, err
	}

	out := make([]*model.Story, 0, len(stories))
	for _, story := range stories {
		out = append(out, &model.Story{
			ID:          story.GetId(),
			Title:       story.GetTitle(),
			Source:      story.GetSource(),
			PublishedAt: story.GetPublishedAt(),
			Sentiment:   float64(story.GetSentiment()),
		})
	}

	return out, nil
}

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
