// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Query struct {
}

type Story struct {
	ID          string  `json:"id"`
	Title       string  `json:"title"`
	Source      string  `json:"source"`
	PublishedAt string  `json:"publishedAt"`
	Sentiment   float64 `json:"sentiment"`
}
